// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Humanizer;
using Microsoft.EntityFrameworkCore;

namespace AttendanceSystem.Models;

public partial class AttendanceSystemContext : DbContext
{
    public AttendanceSystemContext()
    {
    }

    public AttendanceSystemContext(DbContextOptions<AttendanceSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Hr> Hr { get; set; }

    public virtual DbSet<Programs> Programs { get; set; }
    public virtual DbSet<Intakes> Intakes { get; set; }
    public virtual DbSet<Attendance> Attendance { get; set; }
    public virtual DbSet<Admins> Admins { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-JGVAK8U\\SQLEXPRESS;Initial Catalog=AttendanceSystem;Integrated Security=True;TrustServerCertificate=True;Encrypt=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}