// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AttendanceSystem.Models;
public  class Student : User
{
	
    public bool IsVerified { get; set; }

    [ForeignKey("Hr")]
    public int? HrId { get; set; }
    public virtual Hr Hr { get; set; }

    public virtual List<Attendance> attendances { get; set; } = new List<Attendance>();


}