// <auto-generated />
using System;
using AttendanceSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceSystem.Migrations
{
    [DbContext(typeof(AttendanceSystemContext))]
    [Migration("20240828185520_userfullupdate2")]
    partial class userfullupdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int>("StdId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StdId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Department", b =>
                {
                    b.Property<int>("Deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deptid"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Deptid");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Hr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IntakeId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Hr");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Intakes", b =>
                {
                    b.Property<int>("IntakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntakeId"));

                    b.Property<string>("IntakeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntakeId");

                    b.ToTable("Intakes");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Programs", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("ProgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HrId")
                        .HasColumnType("int");

                    b.Property<int?>("IntakeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HrId");

                    b.HasIndex("IntakeId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Attendance", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Student", "Student")
                        .WithMany("attendances")
                        .HasForeignKey("StdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Hr", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Department", "DepartmentNavigation")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("AttendanceSystem.Models.Intakes", "Intake")
                        .WithMany()
                        .HasForeignKey("IntakeId");

                    b.HasOne("AttendanceSystem.Models.Programs", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.Navigation("DepartmentNavigation");

                    b.Navigation("Intake");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Student", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Department", "DepartmentNavigation")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("AttendanceSystem.Models.Hr", "Hr")
                        .WithMany("Students")
                        .HasForeignKey("HrId");

                    b.HasOne("AttendanceSystem.Models.Intakes", "Intake")
                        .WithMany("Students")
                        .HasForeignKey("IntakeId");

                    b.HasOne("AttendanceSystem.Models.Programs", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId");

                    b.Navigation("DepartmentNavigation");

                    b.Navigation("Hr");

                    b.Navigation("Intake");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Hr", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Intakes", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Programs", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Student", b =>
                {
                    b.Navigation("attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
